options:
  formatter: stylish
files:
  include: 'public/app/assets/sass/**/*.scss'
rules:
  property-sort-order: 0
  no-vendor-prefixes: 0
  no-important: 0
  no-duplicate-properties:
  - 1
  -
    exclude:
      - display
