language: node_js

node_js:
  - "8"

before_script:
  - npm install

services:
  - mongodb

script:
  - npm run lint && npm run htmlhint && npm run sasslint && npm test

after_success: npm run coverage
